### ISSUE TITLE
New design applications

### ISSUE THREAD

**Issue by androetto** [pos-cloud/system#219]

**Comment by androetto** [comment]
Jere sigo teniendo el mismo problema te paso ejecutando la query que me pasaste 



![Image](https://github.com/pos-cloud/system/assets/13305254/babbd99d-2f22-4e38-becc-afe2c9938c1a)

y te paso el error 



![Image](https://github.com/pos-cloud/system/assets/13305254/87b55f9c-adf3-49e3-b472-bdf43d219459)

**Comment by Jeremiasvaok** [comment]
["TiendaNube", "Carta digital"].forEach(function(type) {
  var existingDoc = db.getCollection("applications").findOne({ type: type });
  if (!existingDoc) {
      db.getCollection("applications").insertOne({
          type: type,
          name: type.charAt(0).toUpperCase() + type.slice(1), 
          url: 'http://' + type.replace(" ", ""),
          order: type === "TiendaNube" ? 100 : 110
      });
  }
});

**Comment by androetto** [comment]
Jere ejecute la query esa parece que va bien pero ahora tengo este error 



![Image](https://github.com/pos-cloud/system/assets/13305254/130895d6-3748-435d-b362-85450e7343c3)
